site_name: Django REST Live
theme:
  name: readthedocs
  include_homepage_in_sidebar: False
repo_name: https://github.com/pennlabs/django-rest-live
nav:
  - Getting Started:
    - 'installation.md'
    - 'usage.md'
    - 'testing.md'
  - Reference:
    - 'api.md'
    - 'mixin.md'
    - 'router.md'
    - 'signals.md'
